CREATE TABLE orders (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    CustomerName VARCHAR(255) NOT NULL,
    OrderDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TotalAmount DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (Id)
);